version: '2'
services:
  ci-db:
    image: postgres
    container_name: ci-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ci
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "10000:8080"
  ci-back:
    container_name: ci-back
    image: ci-back
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
