version: '2'
services:
  ci-db:
    image: postgres
    container_name: ci-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ci
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "10000:8080"
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    ports:
      - "10001:8080"
    volumes:
      - jenkins_data/:/var/jenkins_home
  sonar:
    container_name: sonarqube
    image: sonarqube:7.8-community
    ports:
      - "10002:9000"

volumes:
  jenkins_data:
